AWSTemplateFormatVersion: '2010-09-09'
Description:
  This template deploys an EC2 instnace using the Nvidia Windows Marketplace AMI in an New VPC (qs-1t26ph9hg)
  
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9006
        - W9901
  AWSAMIRegionMap:
    Filters:
      NVIDIAWIN:
        name: cloudxr-agent-windows-2019-aws-market*
        owner-alias: aws-marketplace
        product-code.type: marketplace
        product-code: bwhppj014bz7uf8lehfv4u8hs

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC configuration
      Parameters:
      - AvailabilityZones
      - VPCCIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR
      - PublicRemoteCidr
    - Label:
        default: VRED Amazon EC2 configuration
      Parameters:
      - WorkloadInstanceType
#      - CloudxrAMI
      - CloudxrStorageVolumeSize
      - KeyPairName
      - InstanceCount
      - PrimaryNodeIP
      - LicenseServerIP
      - VredInstanceTag
    - Label:
        default: VRED media configuration
      Parameters:
      - MediaS3Bucket
      - MediaS3Key
      - SceneAddress
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      VPCCIDR:
        default: VPC CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      WorkloadInstanceType:
        default: Workload servers instance type
      VredInstanceTag:
        default: Tag value for VRED Instance
#      CloudxrAMI:
#        default: Workload servers Cloudxr version
      CloudxrStorageVolumeSize:
        default: Secondary EBS volume size
      KeyPairName:
        default: Key-pair name
      InstanceCount:
        default: Instance Count
      PublicRemoteCidr:
        default: CIDR for customer access
      PrimaryNodeIP:
        default: Primary node IP address
      LicenseServerIP:
        default: Network License Manager IP Address
      MediaS3Bucket:
        default: VRED media S3 bucekt
      MediaS3Key:
        default: VRED media S3 key
      SceneAddress:
        default: The address to a VRED scene file

Parameters:

  AvailabilityZones:
    Description: Availability Zones to use for the subnets in the VPC.
      Three Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the perimeter network located in Availability Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the perimeter network located in Availability Zone 2.
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.160.0/20
    Description: CIDR block for the perimeter network located in Availability Zone 3.
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart
    Description: Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/). The prefix should
      end with a forward slash (/).
    Default: quickstart-nvidia-cloudxr/
    Description: S3 key prefix that is used to simulate a folder for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with 
      a forward slash. See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String    
  KeyPairName:
    Description: Name of an existing EC2 key pair. The instances will launch with
      this key pair.
    Type: AWS::EC2::KeyPair::KeyName        
  WorkloadInstanceType:
    AllowedValues:
    - g4dn.xlarge
    - g4dn.2xlarge
    - g4dn.4xlarge
    - g4dn.8xlarge
    - g4dn.12xlarge
    - g4dn.16xlarge
    - g5.xlarge
    - g5.2xlarge
    - g5.4xlarge
    - g5.8xlarge
    - g5.12xlarge
    - g5.16xlarge
    ConstraintDescription: Must contain valid instance type.
    Default: g4dn.2xlarge
    Description: Type of EC2 instance for the workload instances.
    Type: String
#  CloudxrAMI:
#    Type: String
#    Description: CloudXR Version with Winserver 2019
#    Default: Cloudxr3_1
#    AllowedValues:
#      - Cloudxr3_1
#      - Cloudxr2_1
  VredInstanceTag:
    Type: String
    Default: VRED
    Description: Tag Value for VRED Instances
  CloudxrStorageVolumeSize:
    Type: Number
    Default: 200
    ConstraintDescription: Must be between 1 GB and 16,000 GB (16 TB).
    MinValue: 1
    MaxValue: 16000
    Description: Size of Cloudxr virtualized storage in GBs. 
  InstanceCount:
    Description: Number of EC2 instances for collabration (Excludes Primary Node)
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    ConstraintDescription: Must be a number between 1 and 10.
  PublicRemoteCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Default: 10.0.0.0/16
    Description: CIDR block for the Remote customers.
    Type: String
  PrimaryNodeIP:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Default: 10.0.128.100
    Description: Primary private IP for the first cluster node located in Availability Zone 1 - Prefer PublicsubnetAID.
    Type: String
  LicenseServerIP:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Default: 10.0.128.109
    Description: IP Adrress for VRED NLM Server
    Type: String
  MediaS3Bucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Description: S3 bucket containing VRED installation media
    Type: String
  MediaS3Key:
    ConstraintDescription: The Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Description: S3 key for installation media
    Type: String
  SceneAddress:
    Description: The address to a VRED scene file. It can be an URI or a path in a AWS S3 bucket.
    Type: String
      
#Mappings:
#  AMI:
#    Alias:
#      Cloudxr3_1: /aws/service/marketplace/prod-7msqr5zacq4i6/cloudxr-3.1-vgpu-13.1
#      Cloudxr2_1: /aws/service/marketplace/prod-7msqr5zacq4i6/cloudxr-2.1.29897464-vgpu-12.1
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Mappings:
  AWSAMIRegionMap:
    us-east-1:
      NVIDIAWIN: ami-024836fc2e856676b
    us-east-2:
      NVIDIAWIN: ami-02bbf726b4e66cadc
    us-west-1:
      NVIDIAWIN: ami-0269a87b420e24bbf
    us-west-2:
      NVIDIAWIN: ami-08f6a1cc3966e7664
    ca-central-1:
      NVIDIAWIN: ami-03b9561bfc9ce6bdc
    eu-central-1:
      NVIDIAWIN: ami-0d5bdeb093b8ca54a
    eu-west-1:
      NVIDIAWIN: ami-03754291a37e198cf
    eu-west-2:
      NVIDIAWIN: ami-010d42951441feca5
    eu-west-3:
      NVIDIAWIN: ami-026d2bcf50ded8b2c
    eu-north-1:
      NVIDIAWIN: ami-0388133a2e99c28aa
    eu-south-1:
      NVIDIAWIN: ami-0e73ac91962153a03
    ap-southeast-1:
      NVIDIAWIN: ami-0d087e2dc27fcfb0c
    ap-southeast-2:
      NVIDIAWIN: ami-0cf4fae68ca884e0f
    ap-south-1:
      NVIDIAWIN: ami-0705d258c19d56587
    ap-northeast-1:
      NVIDIAWIN: ami-00ce76c6f171959ab
    ap-northeast-2:
      NVIDIAWIN: ami-044719835f814b445
    ap-east-1:
      NVIDIAWIN: ami-037bcd057531ecf02
    sa-east-1:
      NVIDIAWIN: ami-080198dd0f2e9b7cf
    me-south-1:
      NVIDIAWIN: ami-09f252ba46cca63e5
    af-south-1:
      NVIDIAWIN: ami-02ceb301b599fb738

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones:
          Fn::Join:
          - ','
          - Ref: AvailabilityZones
        NumberOfAZs: '3'
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        CreatePrivateSubnets: 'false'
        CreateNATGateways: 'false'
          
  WorkloadStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnetAID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnetBID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        PublicSubnetCID: !GetAtt VPCStack.Outputs.PublicSubnet3ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        WorkloadInstanceType: !Ref WorkloadInstanceType
#        CloudxrAMI: !Ref CloudxrAMI
        CloudxrStorageVolumeSize: !Ref CloudxrStorageVolumeSize
        KeyPairName: !Ref KeyPairName
        InstanceCount: !Ref InstanceCount
        PublicRemoteCidr: !Ref PublicRemoteCidr
        PrimaryNodeIP: !Ref PrimaryNodeIP
        LicenseServerIP: !LicenseServerIP
        MediaS3Bucket: !Ref MediaS3Bucket
        MediaS3Key: !Ref MediaS3Key
        SceneAddress: !Ref SceneAddress
        VredInstanceTag: !Ref VredInstanceTag
