AWSTemplateFormatVersion: '2010-09-09'
Description:
  This template deploys an EC2 instnace using the Nvidia Windows Marketplace  AMI in an existing VPC
  
Metadata:
  AWSAMIRegionMap:
    Filters:
      NVIDIAWIN:
        name: cloudxr-agent-windows-2019-aws-market*
        owner-alias: aws-marketplace
        product-code.type: marketplace
        product-code: bwhppj014bz7uf8lehfv4u8hs
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC configuration
      Parameters:
      - VPCID
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR

      # See lab instructions
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - WorkloadInstanceType
      - CloudxrAMI
      - CloudxrStorageVolumeSize
      - KeyPairName
      - InstanceCount
      - PublicRemoteCidr
      - QSS3Artifacts
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      VPCID:
        default: VPC CIDR
      PublicSubnetAID:
        default: Public subnet 1 CIDR
      PublicSubnetBID:
        default: Public subnet 2 CIDR
      PublicSubnetCID:
        default: Public subnet 3 CIDR
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3Artifacts:
        default: Quick start S3 Binary store
      WorkloadInstanceType:
        default: Workload servers instance type
      CloudxrAMI:
        default: Workload servers Cloudxr version
      CloudxrStorageVolumeSize:
        default: Secondary EBS volume size
      KeyPairName:
        default: Key-pair name
      InstanceCount:
        default: Instance Count
      PublicRemoteCidr:
        default: CIDR for customer access
Parameters:
  VPCID:
    Description: ID of your existing VPC for deployment
    Type: String
  PublicSubnetAID:
    Description: ID of public subnet in Availability Zone 1.
      for the first node (e.g., subnet-a0246dcd).
    Type: AWS::EC2::Subnet::Id
  PublicSubnetBID:
    Description: ID of public subnet in Availability Zone 2.
      for the second node (e.g., subnet-a0246dcd).
    Type: AWS::EC2::Subnet::Id
  PublicSubnetCID:
    Description: ID of public subnet in Availability Zone 3.
      for the witness (e.g., subnet-a0246dcd).
    Type: AWS::EC2::Subnet::Id
  QSS3Artifacts:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
        letters, uppercase letters, and hyphens (-). It cannot start or end with a
        hyphen (-).
    Default: aws-quickstart-artifacts
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a
      hyphen (-).
    Default: aws-quickstart-vred-cloudxr
    Description: Name of the S3 bucket for your copy of the Quick Start assets.
      Keep the default name unless you are customizing the template.
      Changing the name updates code references to point to a new Quick
      Start location. This name can include numbers, lowercase letters,
      uppercase letters, and hyphens, but do not start or end with a hyphen (-).
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is
    hosted. Keep the default Region unless you are customizing the template.
    Changing this Region updates code references to point to a new Quick Start location.
    When using your own bucket, specify the Region.
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/). The prefix should
      end with a forward slash (/).
    Default: quickstart-starwind-vsan/
    Description: S3 key prefix that is used to simulate a folder for your copy of the
      Quick Start assets. Keep the default prefix unless you are customizing
      the template. Changing this prefix updates code references to point to
      a new Quick Start location. This prefix can include numbers, lowercase
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with
      a forward slash. See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
      and https://aws-quickstart.github.io/option1.html.
    Type: String
  KeyPairName:
    Description: Name of an existing EC2 key pair. The instance will launch with
      this key pair.
    Type: AWS::EC2::KeyPair::KeyName
  WorkloadInstanceType:
    AllowedValues:
    - g4dn.xlarge
    - g4dn.2xlarge
    - g4dn.4xlarge
    - g4dn.8xlarge
    - g4dn.12xlarge
    - g4dn.16xlarge
    ConstraintDescription: Must contain valid instance type.
    Default: g4dn.2xlarge
    Description: Type of EC2 instance for the workload instances.
    Type: String
  CloudxrAMI:
    Type: String
    Description: CloudXR Version with Winserver 2019
    Default: Cloudxr3
    AllowedValues:
      - Cloudxr3
      - Cloudxr2
  CloudxrStorageVolumeSize:
    Type: Number
    Default: 200
    ConstraintDescription: Must be between 1 GB and 16,000 GB (16 TB).
    MinValue: 1
    MaxValue: 16000
    Description: Size of Cloudxr virtualized storage in GBs.
  InstanceCount:
    Description: Number of EC2 instances (must be between 1 and 5).
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    ConstraintDescription: Must be a number between 1 and 10.
  PublicRemoteCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 0.0.0.0/16
    Description: CIDR block for the Remote customers.
    Type: String


Mappings:
  AWSAMIRegionMap:
    us-east-1:
      NVIDIAWIN: ami-024836fc2e856676b
    us-east-2:
      NVIDIAWIN: ami-02bbf726b4e66cadc
    us-west-1:
      NVIDIAWIN: ami-0269a87b420e24bbf
    us-west-2:
      NVIDIAWIN: ami-08f6a1cc3966e7664
    ca-central-1:
      NVIDIAWIN: ami-03b9561bfc9ce6bdc
    eu-central-1:
      NVIDIAWIN: ami-0d5bdeb093b8ca54a
    eu-west-1:
      NVIDIAWIN: ami-03754291a37e198cf
    eu-west-2:
      NVIDIAWIN: ami-010d42951441feca5
    eu-west-3:
      NVIDIAWIN: ami-026d2bcf50ded8b2c
    eu-north-1:
      NVIDIAWIN: ami-0388133a2e99c28aa
    eu-south-1:
      NVIDIAWIN: ami-0e73ac91962153a03
    ap-southeast-1:
      NVIDIAWIN: ami-0d087e2dc27fcfb0c
    ap-southeast-2:
      NVIDIAWIN: ami-0cf4fae68ca884e0f
    ap-south-1:
      NVIDIAWIN: ami-0705d258c19d56587
    ap-northeast-1:
      NVIDIAWIN: ami-00ce76c6f171959ab
    ap-northeast-2:
      NVIDIAWIN: ami-044719835f814b445
    ap-east-1:
      NVIDIAWIN: ami-037bcd057531ecf02
    sa-east-1:
      NVIDIAWIN: ami-080198dd0f2e9b7cf
    me-south-1:
      NVIDIAWIN: ami-09f252ba46cca63e5
    af-south-1:
      NVIDIAWIN: ami-02ceb301b599fb738
#  AMI:
#    Alias:
#      Cloudxr3: /aws/service/marketplace/prod-7msqr5zacq4i6/cloudxr-3.1-vgpu-13.1
#     Cloudxr2: /aws/service/marketplace/prod-7msqr5zacq4i6/cloudxr-2.1.29897464-vgpu-12.1
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart-vred-cloudxr']

Resources:
  WorkstationSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "This security group was generated by AWS Marketplace and is based on recommended settings for NVIDIA CloudXR AMI Introductory Offer - WinServer 2019 version CloudXR 3.1 VGPU 13.1 provided by NVIDIA"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: tcp
          FromPort: 48010
          ToPort: 48010
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: udp
          FromPort: 48010
          ToPort: 48010
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: udp
          FromPort: 47998
          ToPort: 48000
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: udp
          FromPort: 48005
          ToPort: 48005
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: tcp
          FromPort: 47998
          ToPort: 48000
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: tcp
          FromPort: 48005
          ToPort: 48005
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: udp
          FromPort: 48002
          ToPort: 48002
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: tcp
          FromPort: 48002
          ToPort: 48002
          CidrIp: !Ref PublicRemoteCidr
        - IpProtocol: tcp
          FromPort: 8443
          ToPort: 8443
          CidrIp: !Ref PublicRemoteCidr
      VpcId: !Ref VPCID

  WorkstationAccessRole:
    Type: "AWS::IAM::Role"

    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: WorkstationS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - !Sub "arn:aws:s3:::${QSS3Artifacts}"
                  - !Sub "arn:aws:s3:::${QSS3Artifacts}/*"
                  - "arn:aws:s3:::ec2-windows-nvidia-drivers"
                  - "arn:aws:s3:::ec2-windows-nvidia-drivers/*"                                 
        - PolicyName: WorkstationSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: "*"   
  WorkstationAccessProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref WorkstationAccessRole

#  WorkstationEIP:
#    Type: "AWS::EC2::EIP"
#    Properties:
#      Domain: !Ref VPCID

#  WorkstationNI:
#    Type: "AWS::EC2::NetworkInterface"
#    Properties:
#      SubnetId: !Ref PublicSubnetAID
#      GroupSet:
#        - !Ref WorkstationSG


#  AssociateEIP:
#    Type: "AWS::EC2::EIPAssociation"
#    Properties:
#      InstanceId: !Ref WindowsNvidiaWorkstation
#      EIP: !Ref WorkstationEIP

#    WindowsNvidiaWorkstation:
#    Type: 'AWS::EC2::Instance'
#    Properties:
#      ImageId: !Sub
#        - "resolve:ssm:${AmiAlias}"
#        - { AmiAlias: !FindInMap [ AMI, Alias, !Ref CloudxrAMI ] }
#      InstanceType: !Ref WorkloadInstanceType
#      KeyName: !Ref KeyPairName
#      IamInstanceProfile: !Ref 'WorkstationAccessProfile'
#      SecurityGroups: [!Ref 'WorkstationSG']
#      BlockDeviceMappings:
#        - DeviceName: /dev/sda1
#          Ebs:
#            VolumeType: gp2
#            VolumeSize: !Ref CloudxrStorageVolumeSize
#            DeleteOnTermination: 'true'
#            Encrypted: 'false'


  LaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      KeyName: !Ref KeyPairName
      InstanceType: !Ref WorkloadInstanceType
      IamInstanceProfile: !Ref 'WorkstationAccessProfile'
      SecurityGroups: [!Ref 'WorkstationSG']
      ImageId: !FindInMap [AWSAMIRegionMap, !Ref "AWS::Region", NVIDIAWIN]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: !Ref CloudxrStorageVolumeSize
            DeleteOnTermination: 'true'
            Encrypted: 'false'

  WindowsNvidiaWorkstation:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
        VPCZoneIdentifier:
          - !Ref PublicSubnetAID
          - !Ref PublicSubnetBID
          - !Ref PublicSubnetCID
        LaunchConfigurationName: !Ref 'LaunchConfig'
        MinSize: 0
        MaxSize: !Ref InstanceCount
        DesiredCapacity: !Ref InstanceCount